export const LIST_CAMPAIGNS_REQUEST = "LIST_CAMPAIGNS_REQUEST";
export const LIST_CAMPAIGNS_SUCCESS = "LIST_CAMPAIGNS_SUCCESS";
export const LIST_CAMPAIGNS_FAILED = "LIST_CAMPAIGNS_FAILED";

export const ADD_CAMPAIGN_REQUEST = "ADD_CAMPAIGN_REQUEST";
export const ADD_CAMPAIGN_SUCCESS = "ADD_CAMPAIGN_SUCCESS";
export const ADD_CAMPAIGN_FAILED = "ADD_CAMPAIGN_FAILED";
export const ADD_CAMPAIGN_RESET = "ADD_CAMPAIGN_RESET";

export const UPDATE_CAMPAIGN_REQUEST = "UPDATE_CAMPAIGN_REQUEST";
export const UPDATE_CAMPAIGN_SUCCESS = "UPDATE_CAMPAIGN_SUCCESS";
export const UPDATE_CAMPAIGN_FAILED = "UPDATE_CAMPAIGN_FAILED";
export const UPDATE_CAMPAIGN_RESET = "UPDATE_CAMPAIGN_RESET";

export const DELETE_CAMPAIGN_REQUEST = "DELETE_CAMPAIGN_REQUEST";
export const DELETE_CAMPAIGN_SUCCESS = "DELETE_CAMPAIGN_SUCCESS";
export const DELETE_CAMPAIGN_FAILED = "DELETE_CAMPAIGN_FAILED";
export const DELETE_CAMPAIGN_RESET = "DELETE_CAMPAIGN_RESET";
