export const ADD_COMPANY_REQUEST = "ADD_COMPANY_REQUEST";
export const ADD_COMPANY_SUCCESS = "ADD_COMPANY_SUCCESS";
export const ADD_COMPANY_FAILED = "ADD_COMPANY_FAILED";
export const ADD_COMPANY_RESET = "ADD_COMPANY_RESET";

export const LIST_COMPANY_REQUEST = "LIST_COMPANY_REQUEST";
export const LIST_COMPANY_SUCCESS = "LIST_COMPANY_SUCCESS";
export const LIST_COMPANY_FAILED = "LIST_COMPANY_FAILED";

export const UPDATE_COMPANY_REQUEST = "UPDATE_COMPANY_REQUEST";
export const UPDATE_COMPANY_SUCCESS = "UPDATE_COMPANY_SUCCESS";
export const UPDATE_COMPANY_FAILED = "UPDATE_COMPANY_FAILED";
export const UPDATE_COMPANY_RESET = "UPDATE_COMPANY_RESET";

export const DELETE_COMPANY_REQUEST = "DELETE_COMPANY_REQUEST";
export const DELETE_COMPANY_SUCCESS = "DELETE_COMPANY_SUCCESS";
export const DELETE_COMPANY_FAILED = "DELETE_COMPANY_FAILED";
export const DELETE_COMPANY_RESET = "DELETE_COMPANY_RESET";
