export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_FORGET_PASSWORD_INITIATE_REQUEST =
  "USER_FORGET_PASSWORD_INITIATE_REQUEST";
export const USER_FORGET_PASSWORD_INITIATE_SUCCESS =
  "USER_FORGET_PASSWORD_INITIATE_SUCCESS";
export const USER_FORGET_PASSWORD_INITIATE_FAILED =
  "USER_FORGET_PASSWORD_INITIATE_FAILED";
export const USER_FORGET_PASSWORD_INITIATE_RESET =
  "USER_FORGET_PASSWORD_INITIATE_RESET";

export const USER_NEW_PASSWORD_REQUEST = "USER_NEW_PASSWORD_REQUEST";
export const USER_NEW_PASSWORD_SUCCESS = "USER_NEW_PASSWORD_SUCCESS";
export const USER_NEW_PASSWORD_FAILED = "USER_NEW_PASSWORD_FAILED";
export const USER_NEW_PASSWORD_RESET = "USER_NEW_PASSWORD_RESET";

export const USER_ROLE_REQUEST = "USER_ROLE_REQUEST";
export const USER_ROLE_SUCCESS = "USER_ROLE_SUCCESS";
export const USER_ROLE_FAILED = "USER_ROLE_REQUEST";

export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAILED = "CREATE_USER_FAILED";
export const CREATE_USER_RESET = "CREATE_USER_RESET";

export const LIST_USER_REQUEST = "LIST_USER_REQUEST";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const LIST_USER_FAILED = "LIST_USER_FAILED";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";
export const UPDATE_USER_RESET = "UPDATE_USER_RESET";

export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAILED = "DELETE_USER_FAILED";
export const DELETE_USER_RESET = "DELETE_USER_RESET";
