export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_FORGET_PASSWORD_INITIATE_REQUEST =
  "USER_FORGET_PASSWORD_INITIATE_REQUEST";
export const USER_FORGET_PASSWORD_INITIATE_SUCCESS =
  "USER_FORGET_PASSWORD_INITIATE_SUCCESS";
export const USER_FORGET_PASSWORD_INITIATE_FAILED =
  "USER_FORGET_PASSWORD_INITIATE_FAILED";
export const USER_FORGET_PASSWORD_INITIATE_RESET =
  "USER_FORGET_PASSWORD_INITIATE_RESET";

export const USER_NEW_PASSWORD_REQUEST = "USER_NEW_PASSWORD_REQUEST";
export const USER_NEW_PASSWORD_SUCCESS = "USER_NEW_PASSWORD_SUCCESS";
export const USER_NEW_PASSWORD_FAILED = "USER_NEW_PASSWORD_FAILED";
export const USER_NEW_PASSWORD_RESET = "USER_NEW_PASSWORD_RESET";
